import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { z } from "zod";
import { useState, type FormEvent } from "react";
import { ArrowLeft, Database } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { authRequest, authStore, type SessionUser } from "@/lib/auth";
const searchSchema=z.object({mode:z.enum(["login","signup"]).catch("login")});
export const Route=createFileRoute("/auth")({validateSearch:s=>searchSchema.parse(s),head:()=>({meta:[{title:"Account access — pg-router-ai"},{name:"description",content:"Sign in or create a verified pg-router-ai workspace."},{property:"og:title",content:"Account access — pg-router-ai"},{property:"og:description",content:"Secure access to your PostgreSQL control plane."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Auth});
function Auth(){const navigate=useNavigate(),initial=Route.useSearch().mode;const[mode,setMode]=useState<"login"|"signup">(initial),[step,setStep]=useState<"form"|"otp">("form"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
async function submit(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{if(mode==="signup"){if(step==="form"){await authRequest("/auth/signup",{email,password,displayName:name});setStep("otp");}else{const data=await authRequest<{accessToken:string;user:SessionUser}>("/auth/verify",{email,code});authStore.set(data.accessToken);await navigate({to:"/dashboard"});}}else{const data=await authRequest<{accessToken:string;user:SessionUser}>("/auth/login",{email,password});authStore.set(data.accessToken);await navigate({to:"/dashboard"});}}catch(x){setError(x instanceof Error?x.message:"Unable to continue");}finally{setBusy(false)}}
return <div className="mosaic grid min-h-screen md:grid-cols-[1fr_1fr]"><aside className="hidden border-r p-10 md:flex md:flex-col md:justify-between"><Link to="/" className="flex items-center gap-3 font-display font-bold"><span className="grid size-8 place-items-center bg-primary text-primary-foreground"><Database className="size-4"/></span>pg-router-ai</Link><h1 className="font-display text-6xl font-bold leading-[.9] text-primary">Controlled access.<br/>Observable systems.</h1><div className="tech-label">AUTH GATEWAY / TLS REQUIRED / SESSION ROTATION</div></aside><main className="flex items-center justify-center p-5"><div className="relative w-full max-w-[520px] border bg-background p-6 md:p-10"><i className="corner-marker left-[-1px] top-[-1px]"/><i className="corner-marker right-[-1px] top-[-1px] rotate-90"/><Link to="/" className="mb-10 inline-flex items-center gap-2 tech-label"><ArrowLeft className="size-3"/> Return home</Link><div className="mb-8 flex border-b"><button className={`flex-1 border-b-2 py-3 tech-label ${mode==="login"?"border-primary":"border-transparent text-muted-foreground"}`} onClick={()=>{setMode("login");setStep("form")}}>Sign in</button><button className={`flex-1 border-b-2 py-3 tech-label ${mode==="signup"?"border-primary":"border-transparent text-muted-foreground"}`} onClick={()=>{setMode("signup");setStep("form")}}>Create account</button></div><span className="tech-label text-primary">{step==="otp"?"VERIFY / 02":"CREDENTIALS / 01"}</span><h2 className="mt-3 font-display text-3xl font-bold">{step==="otp"?"Check your inbox":mode==="signup"?"Create your workspace":"Welcome back"}</h2><p className="mt-2 text-sm text-muted-foreground">{step==="otp"?`Enter the six-digit code sent to ${email}.`:"Access your database control plane."}</p><form className="mt-8 space-y-5" onSubmit={submit}>{step==="form"&&mode==="signup"&&<Field label="DISPLAY NAME"><Input value={name} onChange={e=>setName(e.target.value)} minLength={2} required/></Field>}{step==="form"&&<><Field label="EMAIL ADDRESS"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label="PASSWORD"><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} required/></Field></>}{step==="otp"&&<Field label="ONE-TIME CODE"><Input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value)} className="h-14 font-mono text-2xl tracking-[.4em]" required/></Field>}{error&&<p className="border-l-2 border-destructive pl-3 text-sm text-destructive">{error}</p>}<Button className="w-full" size="lg" disabled={busy}>{busy?"Processing…":step==="otp"?"Verify account":mode==="signup"?"Send verification code":"Sign in"}</Button></form>{mode==="login"&&<Link to="/reset-password" className="mt-5 block text-center tech-label text-primary">Forgot password?</Link>}</div></main></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label className="tech-label">{label}</Label>{children}</div>}
